name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/**/*'
      - '!frontend/.simple-git-hooks.json'
      - '!frontend/.lintstagedrc.js'
  pull_request:
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/**/*'
      - '!frontend/.simple-git-hooks.json'
      - '!frontend/.lintstagedrc.js'
  workflow_dispatch:

jobs:
  testing:
    name: Test & Analysis
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    env:
      NX_SKIP_NX_CACHE: true

    steps:
      - name: Install Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
      - run: |
          ${{ steps.setup-chrome.outputs.chrome-path }} --version
      - name: Checkout Project Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run check
      - name: Test
        run: npm run test:coverage
        env:
          CI: true
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
      - name: Collect Coverage
        run: |
          COVFILES=$(find packages -wholename '*/.coverage/lcov.info' | tr '\n' ',' | sed '$s/,$//')
          echo "COVFILES=$COVFILES" >> $GITHUB_ENV
      - name: Send Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.COVFILES }}
          flags: unittests
          fail_ci_if_error: true
          root_dir: ${{ github.workspace }}
